version: '3'

services:
  fastapi:
    build:
      context: ./src
      dockerfile: ./compose/Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:src/
    env_file:
      - ./compose/dev/.env
    environment:
      - DOCKER=True

  db:
    image: mongo:latest
    env_file:
      - ./compose/dev/.env
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
